# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef0ee1caf7fec0c4ada2bd87de9e5f9681a9f4a8f4f0e565354c6e90092b6f0df5885c53fb007651c20dec81c4a9970f541a09350bccdf0e280bc825412d3060

test:
  secret_key_base: ae3d9cfea8b820bd07a25af198b43beae35ec1277c357e93f2a8e40feccbe83415a7ed68295c41e9874060a895c966d627dcce3671596175c2bf0cac6d34c8aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
